name: CI

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.6 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install psycopg2
          pip install flask_profiler
          pip install -r requirements.txt
          pip install numpy
          pip install networkx
          pip install matplotlib

          
      # Run our unit tests
      - name: Run unit tests
        run: | 
          python testing.py
          python functionsprofiling.py
          
  
